package sql

import (
	"basic/tools/utils"
)

const HomeCountryTableName = "country"
const HomeCountryTableComment = "用户国家"
const CreateHomeCountryCode = `CREATE TABLE ` + HomeCountryTableName + ` (
	id         	 INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    admin_id   	 INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '管理员ID',
	lang_id 	 INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '语言ID',
    name       	 VARCHAR(50)  NOT NULL DEFAULT '' COMMENT '名称',
	alias		 VARCHAR(50)  NOT NULL DEFAULT '' COMMENT '别名',
	iso1		 CHAR(2) NOT NULL DEFAULT '' COMMENT 'ISO3166-1 二位代码',
    icon       	 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '图标',
    code       	 VARCHAR(50)  NOT NULL DEFAULT '' COMMENT '区号',
    sort       	 TINYINT      NOT NULL DEFAULT 99 COMMENT '排序',
    status     	 TINYINT      NOT NULL DEFAULT 10 COMMENT '状态 -1禁用｜10启用',
    data       	 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '数据',
    created_at 	 INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间'
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='` + HomeCountryTableComment + `';`

const InsertHomeCountry = `INSERT INTO ` + HomeCountryTableName + `(admin_id, name, alias, iso1, icon, code) VALUES
(1, '中国','China', 'CN', '/assets/images/country/china.png', '86'),
(1, '台湾','Taiwan', 'TW', '/assets/images/country/taiwan.png', '886'),
(1, '香港','Hong kong', 'HK', '/assets/images/country/hongkong.png', '852'),
(1, '澳门','Macao', 'MO', '/assets/images/country/macao.png', '853'),
(1, '蒙古','Mongolia', 'MN', '/assets/images/country/mongolia.png', '976'),
(1, '朝鲜','North Korea', 'KP', '/assets/images/country/north_korea.png', '850'),
(1, '韩国','South Korea', 'KR', '/assets/images/country/south_korea.png', '82'),
(1, '日本','Japan', 'JP', '/assets/images/country/japan.png', '81'),
(1, '菲律宾','Philippines', 'PH', '/assets/images/country/philippines.png', '63'),
(1, '越南','Vietnam', 'VN', '/assets/images/country/vietnam.png', '84'),
(1, '老挝','Laos', 'LA', '/assets/images/country/laos.png', '856'),
(1, '柬埔寨','Cambodia', 'kH', '/assets/images/country/cambodia.png', '855'),
(1, '缅甸','Myanmar', 'MM', '/assets/images/country/myanmar.png', '95'),
(1, '泰国','Thailand', 'TH', '/assets/images/country/thailand.png', '66'),
(1, '马来西亚','Malaysia', 'MY', '/assets/images/country/malaysia.png', '60'),
(1, '文莱','Brunei', 'BN', '/assets/images/country/brunei.png', '673'),
(1, '新加坡','Singapore', 'SG', '/assets/images/country/singapore.png', '65'),
(1, '印度尼西亚','Indonesia', 'ID', '/assets/images/country/indonesia.png', '62'),
(1, '东帝汶','Timor-Leste', 'TL', '/assets/images/country/east_timor.png', '670'),
(1, '尼泊尔','Nepal', 'NP', '/assets/images/country/nepal.png', '977'),
(1, '不丹','Bhutan', 'BT', '/assets/images/country/bhutan.png', '975'),
(1, '孟加拉国','Bangladesh', 'BD', '/assets/images/country/bangladesh.png', '880'),
(1, '印度','India', 'IN', '/assets/images/country/india.png', '91'),
(1, '巴基斯坦','Pakistan', 'PK', '/assets/images/country/pakistan.png', '92'),
(1, '斯里兰卡','Sri Lanka', 'LK', '/assets/images/country/sri_lanka.png', '94'),
(1, '马尔代夫','Maldives', 'MV', '/assets/images/country/maldives.png', '960'),
(1, '哈萨克斯坦','Kazakhstan', 'KZ', '/assets/images/country/kazakhstan.png', '7'),
(1, '吉尔吉斯斯坦','Kyrgyzstan', 'KG', '/assets/images/country/kyrgyzstan.png', '996'),
(1, '塔吉克斯坦','Tajikistan', 'TJ', '/assets/images/country/tajikistan.png', '992'),
(1, '乌兹别克斯坦','Uzbekistan', 'UZ', '/assets/images/country/uzbekistan.png', '998'),
(1, '土库曼斯坦','Turkmenistan', 'TM', '/assets/images/country/turkmenistan.png', '993'),
(1, '阿富汗','Afghanistan', 'AF', '/assets/images/country/afghanistan.png', '93'),
(1, '伊拉克','Iraq', 'IQ', '/assets/images/country/iraq.png', '964'),
(1, '伊朗','Iran', 'IR', '/assets/images/country/iran.png', '98'),
(1, '叙利亚','Syria', 'SY', '/assets/images/country/syria.png', '963'),
(1, '约旦','Jordan', 'JO', '/assets/images/country/jordan.png', '962'),
(1, '黎巴嫩','Lebanon', 'LB', '/assets/images/country/lebanon.png', '961'),
(1, '以色列','Israel', 'IL', '/assets/images/country/israel.png', '972'),
(1, '巴勒斯坦','Palestine', 'PS', '/assets/images/country/palestine.png', '970'),
(1, '沙特阿拉伯','Saudi Arabia', 'SA', '/assets/images/country/saudi_arabia.png', '966'),
(1, '巴林','Bahrain', 'BH', '/assets/images/country/bahrain.png', '973'),
(1, '卡塔尔','Qatar', 'QA', '/assets/images/country/qatar.png', '974'),
(1, '科威特','Kuwait', 'KW', '/assets/images/country/kuwait.png', '965'),
(1, '阿拉伯联合酋长国', 'United Arab Emirates', 'AE', '/assets/images/country/united_arab_emirates.png', '971'),
(1, '阿曼','Oman', 'OM', '/assets/images/country/oman.png', '968'),
(1, '也门','Yemen', 'YE', '/assets/images/country/yemen.png', '967'),
(1, '格鲁吉亚','Georgia', 'GE', '/assets/images/country/georgia.png', '995'),
(1, '亚美尼亚','Armenia', 'AM', '/assets/images/country/armenia.png', '374'),
(1, '阿塞拜疆','Azerbaijan', 'AZ', '/assets/images/country/azerbaijan.png', '994'),
(1, '土耳其','Turkey', 'TR', '/assets/images/country/turkey.png', '90'),
(1, '塞浦路斯','Cyprus', 'CY', '/assets/images/country/cyprus.png', '357'),
(1, '英国','England', 'GB', '/assets/images/country/england.png', '44'),
(1, '爱尔兰','Ireland', 'IE', '/assets/images/country/ireland.png', '353'),
(1, '法国','France', 'FR', '/assets/images/country/france.png', '33'),
(1, '荷兰','Netherlands', 'NL', '/assets/images/country/netherlands.png', '31'),
(1, '比利时','Belgium', 'BE', '/assets/images/country/belgium.png', '32'),
(1, '卢森堡','Luxembourg', 'LU', '/assets/images/country/luxembourg.png', '352'),
(1, '摩纳哥','Monaco', 'MC', '/assets/images/country/monaco.png', '377'),
(1, '挪威','Norway', 'NO', '/assets/images/country/norway.png', '47'),
(1, '瑞典','Sweden', 'SE', '/assets/images/country/sweden.png', '46'),
(1, '芬兰','Finland', 'FI', '/assets/images/country/finland.png', '358'),
(1, '丹麦','Denmark', 'DK', '/assets/images/country/denmark.png', '45'),
(1, '冰岛','Iceland', 'IS', '/assets/images/country/iceland.png', '354'),
(1, '法罗群岛','Faroe Islands', 'FO', '/assets/images/country/faroese.png', '298'),
(1, '德国','Germany', 'DE', '/assets/images/country/germany.png', '49'),
(1, '波兰','Poland', 'PL', '/assets/images/country/poland.png', '48'),
(1, '捷克','Czechia', 'CZ', '/assets/images/country/czech.png', '420'),
(1, '斯洛伐克','Slovakia', 'SK', '/assets/images/country/slovakia.png', '421'),
(1, '匈牙利','Hungary', 'HU', '/assets/images/country/hungary.png', '36'),
(1, '奥地利','Austria', 'AT', '/assets/images/country/austria.png', '43'),
(1, '列支敦士登','Liechtenstein', 'LI', '/assets/images/country/liechtenstein.png', '423'),
(1, '瑞士','Switzerland', 'CH', '/assets/images/country/switzerland.png', '41'),
(1, '俄罗斯','Russia', 'RU', '/assets/images/country/russia.png', '7'),
(1, '爱沙尼亚','Estonia', 'EE', '/assets/images/country/estonia.png', '372'),
(1, '拉脱维亚','Latvia', 'LV', '/assets/images/country/latvia.png', '371'),
(1, '立陶宛','Lithuania', 'LT', '/assets/images/country/lithuania.png', '370'),
(1, '白俄罗斯','Belarus', 'BY', '/assets/images/country/belarus.png', '375'),
(1, '乌克兰','Ukraine', 'UA', '/assets/images/country/ukraine.png', '380'),
(1, '摩尔多瓦','Moldova', 'MD', '/assets/images/country/moldova.png', '373'),
(1, '罗马尼亚','Romania', 'RO', '/assets/images/country/romania.png', '40'),
(1, '保加利亚','Bulgaria', 'BG', '/assets/images/country/bulgaria.png', '359'),
(1, '塞尔维亚','Serbia', 'RS', '/assets/images/country/serbia.png', '338'),
(1, '斯洛文尼亚','Slovenia', 'SI', '/assets/images/country/slovenia.png', '386'),
(1, '克罗地亚','Croatia', 'HR', '/assets/images/country/croatia.png', '385'),
(1, '波斯尼亚和黑塞哥维那', 'Bosnia And Herzegovina', 'BA', '/assets/images/country/bosnia_and_herzegovina.png', '387'),
(1, '马其顿','Macedonia', 'MK', '/assets/images/country/macedonia.png', '389'),
(1, '阿尔巴尼亚','Albania', 'AL', '/assets/images/country/albania.png', '355'),
(1, '希腊','Greece', 'GR', '/assets/images/country/greece.png', '30'),
(1, '意大利','Italy', 'IT', '/assets/images/country/italy.png', '39'),
(1, '圣马力诺','San Marino', 'SM', '/assets/images/country/san_marino.png', '378'),
(1, '梵蒂冈','Vatican', 'VA', '/assets/images/country/vatican.png', '379'),
(1, '葡萄牙','Portugal', 'PT', '/assets/images/country/portugal.png', '351'),
(1, '西班牙','Spain', 'ES', '/assets/images/country/spain.png', '34'),
(1, '安道尔','Andorra', 'AD', '/assets/images/country/andorra.png', '376'),
(1, '马耳他','Malta', 'MT', '/assets/images/country/malta.png', '356'),
(1, '埃及','Egypt', 'EG', '/assets/images/country/egypt.png', '20'),
(1, '利比亚','Libya', 'LY', '/assets/images/country/libya.png', '218'),
(1, '苏丹','Sudan', 'SD', '/assets/images/country/sudan.png', '249'),
(1, '突尼西亚','TN', 'HK', '/assets/images/country/tunisia.png', '216'),
(1, '阿尔及利亚','Algeria', 'DZ', '/assets/images/country/algeria.png', '213'),
(1, '摩洛哥','Morocco', 'MA', '/assets/images/country/morocco.png', '212'),
(1, '埃塞俄比亚','Ethiopia', 'ET', '/assets/images/country/ethiopia.png', '251'),
(1, '厄立特里亚','Eritrea', 'ER', '/assets/images/country/eritrea.png', '291'),
(1, '索马里','Somalia', 'SO', '/assets/images/country/somalia.png', '252'),
(1, '吉布提','Djibouti', 'DJ', '/assets/images/country/djibouti.png', '253'),
(1, '肯尼亚','Kenya', 'KE', '/assets/images/country/kenya.png', '254'),
(1, '坦桑尼亚','Tanzania', 'TZ', '/assets/images/country/tasania.png', '255'),
(1, '乌干达','Uganda', 'UG', '/assets/images/country/uganda.png', '256'),
(1, '卢旺达','Rwanda', 'RW', '/assets/images/country/rwanda.png', '250'),
(1, '布隆迪','Burundi', 'BI', '/assets/images/country/burundi.png', '257'),
(1, '塞舌尔','Seychelles', 'SC', '/assets/images/country/seychelles.png', '248'),
(1, '乍得','Chad', 'TD', '/assets/images/country/chad.png', '235'),
(1, '中非','Central Africa', 'CF', '/assets/images/country/central_africa.png', '236'),
(1, '喀麦隆','Cameroon', 'CM', '/assets/images/country/cameroon.png', '237'),
(1, '赤道几内亚','Equatorial Guinea', 'GQ', '/assets/images/country/equatorial_guinea.png', '240'),
(1, '加蓬','Gabon', 'GA', '/assets/images/country/gabon.png', '241'),
(1, '刚果','Congo', 'CG', '/assets/images/country/congo.png', '242'),
(1, '圣多美和普林西比','Sao Tome And Principe', 'ST', '/assets/images/country/sao_tome_and_principe.png', '239'),
(1, '毛里塔尼亚','Mauritania', 'MR', '/assets/images/country/mauritania.png', '222'),
(1, '塞内加尔','Senegal', 'SN', '/assets/images/country/senegal.png', '221'),
(1, '冈比亚','Gambia', 'GM', '/assets/images/country/gambia.png', '220'),
(1, '马里','Mali', 'ML', '/assets/images/country/mali.png', '223'),
(1, '布基纳法索','Burkina Faso', 'BF', '/assets/images/country/burkina_faso.png', '226'),
(1, '几内亚','Guinea', 'GN', '/assets/images/country/guinea.png', '224'),
(1, '几内亚比绍','Guinea Bissau', 'GW', '/assets/images/country/guinea_bissau.png', '245'),
(1, '佛得角','Cape Verde', 'CV', '/assets/images/country/cape_verde.png', '238'),
(1, '塞拉利昂','Sierra Leone', 'SL', '/assets/images/country/sierra_leone.png', '232'),
(1, '利比里亚','Liberia', 'LR', '/assets/images/country/liberia.png', '231'),
(1, '科特迪瓦','Ivory Coast', 'CI', '/assets/images/country/ivory_coast.png', '225'),
(1, '加纳','Ghana', 'GH', '/assets/images/country/ghana.png', '233'),
(1, '多哥','Togo', 'TG', '/assets/images/country/togo.png', '228'),
(1, '贝宁','Benin', 'BJ', '/assets/images/country/benin.png', '229'),
(1, '尼日尔','Niger', 'NE', '/assets/images/country/niger.png', '227'),
(1, '尼日利亚','Nigeria', 'NG', '/assets/images/country/nigeria.png', '234'),
(1, '西撒哈拉','Western Sahara', 'EH', '/assets/images/country/western_sahara.png', '210'),
(1, '赞比亚','Zambia', 'ZM', '/assets/images/country/zambia.png', '260'),
(1, '安哥拉','Angola', 'AO', '/assets/images/country/angola.png', '244'),
(1, '津巴布韦','Zimbabwe', 'ZW', '/assets/images/country/zimbabwe.png', '263'),
(1, '马拉维','Malawi', 'MW', '/assets/images/country/malawi.png', '265'),
(1, '莫桑比克','Mozambique', 'MZ', '/assets/images/country/mozambique.png', '258'),
(1, '博茨瓦纳','Botswana', 'BW', '/assets/images/country/botswana.png', '267'),
(1, '纳米比亚','Namibia', 'NA', '/assets/images/country/namibia.png', '264'),
(1, '南非','South Africa', 'ZA', '/assets/images/country/south_africa.png', '27'),
(1, '斯威士兰','Eswatini', 'SZ', '/assets/images/country/swaziland.png', '268'),
(1, '莱索托','Lesotho', 'LS', '/assets/images/country/Lesotho.png', '266'),
(1, '马达加斯加','Madagascar', 'MG', '/assets/images/country/madagascar.png', '261'),
(1, '科摩罗','Comoros', 'KM', '/assets/images/country/comoros.png', '269'),
(1, '毛里求斯','Mauritius', 'MU', '/assets/images/country/Mauritius.png', '230'),
(1, '圣赫勒拿岛','Saint Helena', 'SH', '/assets/images/country/st_helena.png', '290'),
(1, '马约特','Mayotte', 'YT', '/assets/images/country/mayotte.png', '262'),
(1, '加拿大','Canada', 'CA', '/assets/images/country/canada.png', '1'),
(1, '美国','United States', 'US', '/assets/images/country/usa.png', '1'),
(1, '墨西哥','Mexico', 'MX', '/assets/images/country/mexico.png', '52'),
(1, '格陵兰','Greenland', 'GL', '/assets/images/country/greenland.png', '299'),
(1, '圣皮埃尔和密克隆','Saint Pierre and Miquelon', 'PM', '/assets/images/country/saint_pierre_and_miquelon.png', '508'),
(1, '百慕大','Bermuda', 'BM', '/assets/images/country/bermuda.png', '441'),
(1, '危地马拉','Guatemala', 'GT', '/assets/images/country/guatemala.png', '502'),
(1, '伯利兹','Belize', 'BZ', '/assets/images/country/belize.png', '501'),
(1, '萨尔瓦多','Salvador', 'SV', '/assets/images/country/salvador.png', '503'),
(1, '洪都拉斯','Honduras', 'HN', '/assets/images/country/honduras.png', '504'),
(1, '尼加拉瓜','Nicaragua', 'NI', '/assets/images/country/nicaragua.png', '505'),
(1, '哥斯达黎加','Costa Rica', 'CR', '/assets/images/country/costa_rica.png', '506'),
(1, '巴拿马','Panama', 'PA', '/assets/images/country/panama.png', '507'),
(1, '巴哈马','Bahamas', 'BS', '/assets/images/country/bahamas.png', '1242'),
(1, '古巴','Cuba', 'CU', '/assets/images/country/cuba.png', '53'),
(1, '牙买加','Jamaica', 'JM', '/assets/images/country/jamaica.png', '1876'),
(1, '海地','Haiti', 'HT', '/assets/images/country/haiti.png', '509'),
(1, '多米尼加共和国','Dominican Republic', 'DO', '/assets/images/country/dominica_republic.png', '1809'),
(1, '安提瓜和巴布达','Antigua And Barbuda', 'AG', '/assets/images/country/antigua_and_barbuda.png', '1268'),
(1, '圣基茨和尼维斯','Saint Kitts And Nevis', 'KN', '/assets/images/country/saint_kitts_and_nevis.png', '1869'),
(1, '多米尼克','Dominica', 'DM', '/assets/images/country/dominica.png', '1767'),
(1, '圣卢西亚','Saint Lucia', 'LC', '/assets/images/country/saint_lucia.png', '1758'),
(1, '圣文森特和格林纳丁斯','Saint Vincent And The Grenadines', 'VC', '/assets/images/country/saint_vincent_and_the_grenadines.png', '784'),
(1, '格林纳达','Grenada', 'GD', '/assets/images/country/grenada.png', '1473'),
(1, '巴巴多斯','Barbados', 'BB', '/assets/images/country/barbados.png', '1246'),
(1, '特立尼达和多巴哥','Trinidad And Tobago', 'TT', '/assets/images/country/trinidad_and_tobago.png', '1868'),
(1, '波多黎各','Puerto Rico', 'PR', '/assets/images/country/puerto_rico.png', '1787'),
(1, '英属维尔京群岛','The British Virgin Islands', 'VG', '/assets/images/country/the_british_virgin_islands.png', '1284'),
(1, '美属维尔京群岛','United States Virgin Islands', 'VI', '/assets/images/country/united_states_virgin_islands.png', '1340'),
(1, '安圭拉','Anguilla', 'AI', '/assets/images/country/anguilla.png', '264'),
(1, '蒙特塞拉特','Montserrat', 'MS', '/assets/images/country/montserrat.png', '1664'),
(1, '瓜德罗普','Guadeloupe', 'GP', '/assets/images/country/guadeloupe.png', '590'),
(1, '马提尼克','Martinique', 'MQ', '/assets/images/country/martinique.png', '596'),
(1, '阿鲁巴','Aruba', 'AW', '/assets/images/country/aruba.png', '297'),
(1, '法属圣马丁','Saint Martin', 'MF', '/assets/images/country/st_martin.png', '1721'),
(1, '特克斯和凯科斯群岛','Turks And Caicos Islands', 'TC', '/assets/images/country/turks_and_caicos_islands.png', '1649'),
(1, '开曼群岛','Cayman Islands', 'KY', '/assets/images/country/cayman_islands.png', '1345'),
(1, '库拉索','Curacao', 'CW', '/assets/images/country/curacao.png', '5999'),
(1, '哥伦比亚','Colombia', 'CO', '/assets/images/country/colombia.png', '57'),
(1, '委内瑞拉','Venezuela', 'VE', '/assets/images/country/venezuela.png', '58'),
(1, '圭亚那','Guyana', 'GY', '/assets/images/country/guyana.png', '592'),
(1, '苏里南','Suriname', 'SR', '/assets/images/country/suriname.png', '597'),
(1, '法属圭亚那','French Guiana', 'GF', '/assets/images/country/french_guiana.png', '594'),
(1, '厄瓜多尔','Ecuador', 'EC', '/assets/images/country/ecuador.png', '593'),
(1, '秘鲁','Peru', 'PE', '/assets/images/country/peru.png', '51'),
(1, '玻利维亚','Bolivia', 'BO', '/assets/images/country/bolivia.png', '591'),
(1, '巴西','Brazil', 'BR', '/assets/images/country/brazil.png', '55'),
(1, '智利','Chile', 'CL', '/assets/images/country/chile.png', '56'),
(1, '阿根廷','Argentina', 'AR', '/assets/images/country/argentina.png', '54'),
(1, '乌拉圭','Uruguay', 'UY', '/assets/images/country/uruguay.png', '598'),
(1, '巴拉圭','Paraguay', 'PY', '/assets/images/country/paraguay.png','595'),
(1, '澳大利亚','Australia', 'AU', '/assets/images/country/australia.png', '61'),
(1, '新西兰','New Zealand', 'NZ', '/assets/images/country/new_zealand.png', '64'),
(1, '帕劳','Palau', 'PW', '/assets/images/country/palau.png', '680'),
(1, '密克罗尼西亚联邦','Federated States Of Micronesia', 'FM', '/assets/images/country/federated_states_of_micronesia.png', '691'),
(1, '马绍尔群岛','Marshall Islands', 'MH', '/assets/images/country/marshall_islands.png', '692'),
(1, '基里巴斯','Kiribati', 'KI', '/assets/images/country/kiribati.png', '686'),
(1, '瑙鲁','Nauru', 'NR', '/assets/images/country/nauru.png', '674'),
(1, '北马里亚纳','Northern Mariana', 'MP', '/assets/images/country/northern_mariana.png', '670'),
(1, '关岛','Guam', 'GU', '/assets/images/country/guam.png', '1671'),
(1, '巴布亚新几内亚','Papua New Guinea', 'PG', '/assets/images/country/papua_new_guinea.png', '675'),
(1, '所罗门群岛','Solomon Islands', 'SB', '/assets/images/country/solomon_islands.png', '677'),
(1, '瓦努阿图','Vanuatu', 'VU', '/assets/images/country/vanuatu.png', '678'),
(1, '斐济','Fiji', 'FJ', '/assets/images/country/fiji.png', '679'),
(1, '图瓦卢','Tuvalu', 'TV', '/assets/images/country/tuvalu.png', '688'),
(1, '萨摩亚','Samoa', 'WS', '/assets/images/country/samoa.png', '685'),
(1, '汤加','Tonga', 'TO', '/assets/images/country/tonga.png', '676'),
(1, '库克群岛','Cook Islands', 'CK', '/assets/images/country/island.png', '682'),
(1, '纽埃','Niue', 'NU', '/assets/images/country/niue.png', '683'),
(1, '托克劳','Tokelau', 'TK', '/assets/images/country/tokelau.png', '690'),
(1, '瓦利斯和富图纳','Wallis And Futuna', 'WF', '/assets/images/country/wallis_and_futuna.png', '681'),
(1, '皮特凯恩群岛','Pitcairn Islands', 'PN', '/assets/images/country/pitcairn_islands.png', '649'),
(1, '美属萨摩亚','American Samoa', 'AS', '/assets/images/country/american_samoa.png', '684');`

var BasicHomeCountry = &utils.InitTable{
	Name:        HomeCountryTableName,
	Comment:     HomeCountryTableComment,
	CreateTable: CreateHomeCountryCode,
	InsertTable: InsertHomeCountry,
}
